name: TestPlugin
main: fr.jak12210.Main
version: 1.0
author: jak12210
commands:
  rules:
    description: See the server rules
    aliases: [regles]
  gm:
    description: Change the gamemode
  gamemode:
    description: Change the gamemode
  lang:
    description: Change the lang
  language:
    description: Change the lang
  langue:
    description: Change the lang
  money:
    description: See your balance
    aliases: [balance, argent]
  addmoney:
    description: Add money to a player
  delmoney:
    description: Remove money to a player
  setmoney:
    description: Set the money to a player
  givemoney:
    description: Give money to a player
  broadcaster:
    description: Start/Stop the broadcaster